# Site settings
title: Brennan Willingham | Software Developer
email: brennanw22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Brennan WIllingham and I am awesome web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Brenntron
github_username:  Brenntron

# Build settings
markdown: kramdown

gems: [bourbon, neat, github-pages]
