# Site settings
title: Brennan Willingham | Code Crafter
email: brennanw22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Brennan Willingham and I have a passion for creating and technology!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brennanwillingham.com" # the base hostname & protocol for your site
twitter_username: Brenntron
github_username:  Brenntron
linkedin_url: brennanwillingham

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]


plugins: [bourbon, neat, github-pages]

author:
  name: Brennan Willingham
  email: brennanw22@gmail.com
  github: brenntron
  twitter: brenntron
